# GitHub Sponsors / Donation configuration
buy_me_a_coffee: arpmag
custom:
  - 'https://send.monobank.ua/jar/8HBjkw7ZT5'
  - 'https://donatello.to/widget/6a943d6f5649df604b787dd1/token/0b77d459fc1e8838cd9fd6b94fa86c78'
